# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and run tests"
  lane :test do
    scan(scheme: "insurobo")
  end

  #버젼설정
  def updateVersion(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "Enter the version type or specific version\n(major, minor, patch or 1.0.0): ")
    end

    re = /\d+.\d+.\d+/
    versionNum = version[re, 0]

    if (versionNum)
      increment_version_number(
        version_number: versionNum
      )
    elsif (version == 'major' || version == 'minor' || version == 'patch')
      increment_version_number(
        bump_type: version
      )
    else
      UI.user_error!("[ERROR] Wrong version!!!!!!")
    end
  end

  lane :beta do | options |
    desc "TesfFlight for IOS"
    updateVersion(options)
    increment_build_number(xcodeproj: "insurobo.xcodeproj")
    # Circle CI does not create new code signing certificates or provisioning profiles.
    sync_code_signing(type: "appstore", readonly: true, app_identifier: "com.insurobo.insurobo") # Bundle Identifier를 아까 만든 값으로 치환한다.
    # see code signing guide for more information, readonly because of CircleCI
    build_app(scheme: "insurobo")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      channel: "#app-deploy",
      message: "ios testflight 배포완료",
    )
  end
end

lane :increase_build_number_and_push_to_beta do |values|
    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(xcodeproj: "insurobo.xcodeproj")
    # Commit the version bump
    commit_version_bump(xcodeproj: "insurobo.xcodeproj", force: true)
    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    # add_git_tag
    # # Push the new commit and tag back to your git remote
    # push_to_git_remote(
    #     remote_branch: "master", # optional, default is set to local_branch
    #     force: true,    # optional, default: false
    # )
end