# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Firebase_app_distribution"
    lane :distribute do |options|
	updateVersion(options)
        build_android_app(task: "assembleRelease") 
	# build_android_app is a built-in fastlane action.

        firebase_app_distribution(
            app: "1:32734331599:android:ec01c38daf496698cd6dba",
            firebase_cli_token: "1//0e5EfTyPY-rpyCgYIARAAGA4SNwF-L9Ir7lNADseVtHp-8Q_rfZTp0XNssaOk_kEir8sX5VXB9-zeBjjq5onHvgR7o9YOHjPSSVo",
            groups: "인슈로보내부",
            release_notes: "자동배포 테스트"
        )

    end
end
